### ISSUE TITLE
Stable version is bugged.

### ISSUE THREAD

**Issue by mariushosting** [convos-chat/convos#810]
When I try to install :stable version I always get 

**Could not source /app/cpanfile: Invalid argument**

**Comment by mariushosting** [comment]
> Have you tried any of the other tags https://hub.docker.com/r/convos/convos/tags ?
> 
> It's hard to know what might be wrong, when I don't know your complete setup.

Hello Jan,

Yes, I can assure you only convos/convos:v6.32 works but not different tags. This happens on a Synology NAS devices, all the version after v6.32 stopped works. Only the version v6.32 still works without any issue. So something has changed months ago after version v6.32

https://mariushosting.com/how-to-install-convos-on-your-synology-nas/

**Comment by jhthorsen** [comment]
That is very strange, since I'm currently using "convos/convos:v7.13".

But is Synology x86 or arm? (I'm using x86)

**Comment by mariushosting** [comment]
> That is very strange, since I'm currently using "convos/convos:v7.13".
> 
> But is Synology x86 or arm? (I'm using x86)

Hello Jan,

I'm using an x86 Model. I have tried different x86 models same results only convos 6.32 works. https://www.synology.com/en-global/products/DS1621xs+#specs

This particular container stop to works on a Synology NAS System just after 6.32 version. The issue started with version 6.33 
I'm also getting different emails from user that report this to me. So I have decided to reach you :-)
No issue on over 250 containers https://mariushosting.com/docker/

**Comment by jhthorsen** [comment]
I'm looking at the Dockerfiles side by side, and I can't say I can spot it. I'll try to look at it again once I find time.

**Comment by mariushosting** [comment]
Thank you Jan!

**Comment by jhthorsen** [comment]
I think I fixed this in the [alpha](https://hub.docker.com/layers/convos/convos/alpha/images/sha256-0bbdbafd903b7016900051c8d7e1f4fba847cc3368fd8d888e698be1b9536190?context=explore) tag.

Can you try that one before I push it to stable?

**Comment by mariushosting** [comment]
> I think I fixed this in the [alpha](https://hub.docker.com/layers/convos/convos/alpha/images/sha256-0bbdbafd903b7016900051c8d7e1f4fba847cc3368fd8d888e698be1b9536190?context=explore) tag.
> 
> Can you try that one before I push it to stable?

Give me about 10 minutes. I will get back to you!

**Comment by mariushosting** [comment]
@jhthorsen Still not working. Here is the log:

 Name                           Required   Installed 
  perl                           5.020      v5.32.1    
  Unicode::UTF8                  0.62       0.62       
  Time::Piece                    1.20       1.3401     
  Text::Markdown::Hoedown        1.03       1.03       
  Syntax::Keyword::Try           0.27       0.28       
  Parse::IRC                     1.22       1.22       
  Mojolicious::Plugin::Syslog    0.06       0.06       
  Mojolicious::Plugin::OpenAPI   5.07       5.08       
  Mojolicious                    9.31       9.31       
  Module::Install                1.10       1.19       
  LinkEmbedder                   1.20       1.20       
  IRC::Utils                     0.12       0.12       
  IO::Socket::SSL                2.009      2.071      
  HTTP::AcceptLanguage           0.02       0.02       
  Future::AsyncAwait             0.59       0.62       
  File::ReadBackwards            1.06       1.06       
  File::HomeDir                  1.00       1.006      
  Crypt::Passphrase::Bcrypt      0.003      0.003      
  Crypt::Passphrase::Argon2      0.003      0.003      
  Crypt::Passphrase              0.004      0.005      
  Convos                         7.13       7.13       
It is not possible to start Convos at this point, since there
are some missing dependencies that need to be installed.
Run "/app/script/convos install" to install the missing dependencies above.

**Comment by jhthorsen** [comment]
Wow! What a silly bug from my side. Can you try again?

**Comment by mariushosting** [comment]
> Wow! What a silly bug from my side. Can you try again?

on it!

**Comment by mariushosting** [comment]
PERFECT! @jhthorsen issue fixed! I can confirm it's working perfectly on a Synology NAS! Great job!
![perfect](https://user-images.githubusercontent.com/37554361/211693799-fc3e1c9d-acf1-4e2c-99ee-41550786bc0c.png)

**Comment by jhthorsen** [comment]
Convos v7.14 (stable) is soon available on https://hub.docker.com/r/convos/convos/tags

**Comment by mariushosting** [comment]
@jhthorsen Everything works like a charm!

**Comment by jhthorsen** [comment]
Great news!
