### ISSUE TITLE
Admin email setting adds "mailto:" every time I press "save settings"

### ISSUE THREAD

**Issue by poVoq** [convos-chat/convos#813]
Admin email setting adds "mailto:" every time I press "save settings", which is a bit annoying.

In general it would be probably nice if the setting field would also allow just any URL, in case you prefer other means of contact.

**Comment by jhthorsen** [comment]
This is fixed in Convos v7.14. You can also enter "https://example.com" if you like.

**Comment by poVoq** [comment]
Small bug still:

On the /login page the link to contact the admin works as expected with arbitrary links, but on the /register page the big button only changes the URL in the browser URL bar but does not actually redirect to the site.
